theme: jekyll-theme-midnight
title: Regene's Portfolio
tagline: Curious about Data, Driven by Questions. Learning through Analysis
description: Welcome to my portfolio! I am an Applied Mathematics graduate exploring the world of data analytics and data science. Here, I share projects where I apply my knowledge to explore real-world and academic datasets.
